### PR TITLE
Pass flow attr to subflow

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[*] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #
Pass flow attr to subflow
**What is the current behavior?**

**What is the new behavior?**

### CODE REVIEW

**Comment by mellistibco** [comment]
This isn't right. If you want any data from the flow attr to be passed into the subflow then you should map the data into the flow input, as desired...

**Comment by lixingwang** [comment]
@mellistibco  that what we discussed to share flow data in a flow instance.   the data set in the main flow should able to get in subflow.

**Comment by mellistibco** [comment]
sorry @lixingwang I must not have understood correctly when we discussed... I don't feel that we should be passing into a parents inputs to the subflow... The user will need to explicitly map the data into the subflow call using the flow inputs for that subflow being called.

**Comment by lixingwang** [comment]
For this kind of use cases, we can use flow input + update object activity https://github.com/project-flogo/contrib/tree/master/activity/updobject

**Pull request closed without merging**
