### PR TITLE
Increase default step count to 10M and expose to env variable 

### PR DESCRIPTION
**Pull request by vanilcha-tibco**
**Fixes**: #

**What is the current behavior?**
Flow goes into the stalled state after the step count is reached (1M)

**What is the new behavior?**
Flow will propagate the error when max step count is reached.

### CODE REVIEW

**Comment by ayh20** [comment]
I think this needs to be done in a better way. This just increases us from one arbitrary limit to another, at least make it the contents of an int.
Also having this as something we can set seems odd ... if you have a process that's going to loop and hit the limit how will the task starter ever know what to see the limit too ?

**Comment by ayh20** [comment]
And the other issue is that at present when the limit is hit, processing halts but no error is thrown, so there's no way to know if you've hit the limit

**Review by vnalawad-tibco — CHANGES_REQUESTED** [review]

**Review by vnalawad-tibco — APPROVED** [review]
LGTM

**Review by awakchau-tibco — APPROVED** [review]

**Review by abhijitWakchaure — APPROVED** [review]
LGTM

**Review by abhijitWakchaure — APPROVED** [review]

**Pull request merged**
