### PR TITLE
Change otherwise link type to exprOtherwise

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[*] Other... Please describe:
```
Today we do have the default, label, expression and error link types, The otherwise makes more confusing for the user to understand. 

The current behavior is: Execute otherwise branch when only there is no other link be executed. 

After discussing with @fm-tibco @vijaynalawade we agreed to change it to exprOtherwise,  it is only for expression type.  Just like the condition with condition false

**Fixes**: #

**What is the current behavior?**

**What is the new behavior?**

### CODE REVIEW

**Comment by lixingwang** [comment]
@mellistibco  Please let me know your thoughts?

**Comment by fm-tibco** [comment]
Should it be `LtExprOtherwise` or `LtExprElse` or `LtExpressionElse`

**Comment by fm-tibco** [comment]
@fcastill is the Flogo UI using "otherwise" link type?

**Comment by fcastill** [comment]
@fm-tibco nope, only "default" and "expression"

**Comment by vijaynalawade** [comment]
> Should it be `LtExprOtherwise` or `LtExprElse` or `LtExpressionElse`

@fm-tibco I think `LtExprOtherwise` is better.

**Comment by fm-tibco** [comment]
@mellistibco thoughts?

**Comment by mellistibco** [comment]
I like `LtExprOtherwise`

**Comment by lixingwang** [comment]
Thanks, @mellistibco, and  @mellistibco  @fm-tibco, please approve PR.

**Comment by vijaynalawade** [comment]
@fm-tibco @mellistibco : Please approve PR

**Pull request merged**
