### PR TITLE
Add delay and index to dowhile

### PR DESCRIPTION
**Pull request by cpramodroy**
**What kind of change does this PR introduce?** (check one with "x")
```
[] Bugfix
[x] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**
Currently, do while iterates indefinitely and immediately if the condition evaluates to true.
**What is the new behavior?**
User has the option to delay each repetition by a specific interval or limit the number of iteration by using `$dowhile["index"]` as part of the do while condition. Here, `dowhile["index"]` tracks the iteration index for the do while behavior. 
-- Added a new "dowhile" resolver
-- Updated the scope while evaluating the expression.
-- Changed some Debug logs to INFO to provide the user more information about each iteration

See example below:
```json
{
    "imports": [
        "github.com/project-flogo/flow",
        "github.com/project-flogo/contrib/activity/log",
        "github.com/project-flogo/contrib/activity/rest",
        "github.com/project-flogo/contrib/activity/actreturn",
        "github.com/project-flogo/contrib/trigger/timer"
    ],
    "name": "doWhileApp",
    "description": " ",
    "version": "1.1.0",
    "type": "flogo:app",
    "appModel": "1.1.0",
    "feVersion": "2.7.0",
    "triggers": [
        {
            "ref": "#timer",
            "name": "Timer",
            "description": "Simple Timer trigger",
            "settings": {},
            "id": "Timer",
            "handlers": [
                {
                    "description": "",
                    "settings": {},
                    "action": {
                        "ref": "github.com/project-flogo/flow",
                        "settings": {
                            "flowURI": "res://flow:f1"
                        }
                    }
                }
            ]
        }
    ],
    "resources": [
        {
            "id": "flow:f1",
            "data": {
                "name": "f1",
                "description": "",
                "links": [
                    {
                        "id": 1,
                        "from": "Log",
                        "to": "RESTInvoke",
                        "type": "default"
                    },
                    {
                        "id": 2,
                        "from": "RESTInvoke",
                        "to": "Return",
                        "type": "default"
                    }
                ],
                "tasks": [
                    {
                        "id": "Log",
                        "name": "Log",
                        "description": "Logs a message",
                        "activity": {
                            "ref": "#log",
                            "input": {
                                "message": "running dowhile example",
                                "addDetails": false
                            }
                        }
                    },
                    {
                        "id": "RESTInvoke",
                        "name": "RESTInvoke",
                        "description": "Invokes a REST Service",
                        "settings": {
			"doWhile": {
				"condition":"$activity[RESTInvoke].data.username == \"Bret\" && $dowhile[\"index\"]<=3",
				"delay": 2000
			},
			"retryOnError": {
				"count": 3,
				"interval": 2000
			}
                      },
                        "type": "doWhile",
                        "activity": {
                            "ref": "#rest",
                            "settings": {
                                "method": "GET",
                                "uri": "https://jsonplaceholder.typicode.com/users/1",
                                "headers": "",
                                "proxy": "",
                                "timeout": 0,
                                "sslConfig": ""
                            },
                            "input": {
                                "pathParams": "",
                                "queryParams": "",
                                "headers": ""
                            }
                        }
                    },
                    {
                        "id": "Return",
                        "name": "Return",
                        "description": "Simple Return Activity",
                        "activity": {
                            "ref": "#actreturn"
                        }
                    }
                ],
                "metadata": {
                    "input": [],
                    "output": [],
                    "fe_metadata": {}
                }
            }
        }
    ],
    "properties": [],
    "contrib": "W3sicmVmIjoiZ2l0aHViLmNvbS9wcm9qZWN0LWZsb2dvL2NvbnRyaWIvdHJpZ2dlci90aW1lciIsInMzbG9jYXRpb24iOiJ7VVNFUklEfS9EZWZhdWx0L3RyaWdnZXIvdGltZXIifSx7InJlZiI6ImdpdGh1Yi5jb20vcHJvamVjdC1mbG9nby9jb250cmliL2FjdGl2aXR5L2xvZyIsInMzbG9jYXRpb24iOiJ7VVNFUklEfS9EZWZhdWx0L2FjdGl2aXR5L2xvZyJ9LHsicmVmIjoiZ2l0aHViLmNvbS9wcm9qZWN0LWZsb2dvL2NvbnRyaWIvYWN0aXZpdHkvcmVzdCIsInMzbG9jYXRpb24iOiJ7VVNFUklEfS9EZWZhdWx0L2FjdGl2aXR5L3Jlc3QifV0=",
    "fe_metadata": "UEsDBAoAAAAIAEOkCE+rqSRGFQAAABMAAAAIAAAAYXBwLmpzb26rViopykxPTy1yy8kvL1ayio6tBQBQSwECFAAKAAAACABDpAhPq6kkRhUAAAATAAAACAAAAAAAAAAAAAAAAAAAAAAAYXBwLmpzb25QSwUGAAAAAAEAAQA2AAAAOwAAAAAA"
}
```

Output:
image

### CODE REVIEW

**Comment by fm-tibco** [comment]
What is the use-case for delay (i'm assuming this is a sleep/wait interval between loops)?  Also, should we have a seperate resolver or just use $loop and make it work for both iteration and while loop.  We can make it uniform and add `count` to both.

**Comment by cpramodroy** [comment]
To use `$loop` to track index for both iteration and while loop, it needs to be accessed as `$loop["index"]`. This will work for dowhile because I am creating a new simple scope to track the index and passing that scope to eval. But in case of iteration, I do have access to modifying the scope but can add the index to the working data. The `loop` resolver however does not look at working data when trying to resolve the value. I'd have to create a special case for when `item` is `"index"` which is not ideal.

The other alternative is to use `iteration["index"]` for both dowhile and iterator.

**Comment by lixingwang** [comment]
@fm-tibco  There are some issues to re-use $loop.  Take an example here,  we iterator/dowhile on an activity which has array mapping that means in the array mapping it has high possibility to use `$loop[key]` or `$loop[value]` or `$loop[index]`,  it will difficult to know it comes from iterator or array mapping itself.

For this kind of case, it's better to come up with a new resolver which can be used in both iterator and dowhile.

**Comment by fm-tibco** [comment]
Not sure why it is an issue to use count, just add a counter to both.  Or use index for both, isn’t that just a count as well?

**Comment by lixingwang** [comment]
@fm-tibco  the counter or indexer is not an issue.  let me explain more details

Assume we use $loop for iterator and dowhile, which means we use `$loop[key]` and `$loop[value]` to access iteration key and value.

Now we do have an array mapping in activity input which has iterator enabled. 
```
{
  "books": {
    "mapping": {
      "@foreach($flow.store.books, value)": {
        "title": "=$loop.title",
        "price": "=$loop.price",
        "author": {
         "@foreach($loop.author, authorLoop)": {
            "lastName": "=$loop[authorLoop].lastName",
            "bookTitle": "=$loop[value].title"
         }
        }
      }
    }
  }
}
```

See the above example where we define books array mapping scope name as `value`, and we use `=$loop[value].title` in nested array to access parent loop data.

Now the issue is `=$loop[value].title` we don't know it access iterator value or array data.

Maybe we can use $iteration for dowhile as well, @fm-tibco thoughts?

**Comment by fm-tibco** [comment]
Maybe we should have a zoom. I’m not sure why the previous comment precludes having a $loop[count/index] that applies to both iterator and do-while.  For iterator it will additionally have key and value.

**Pull request merged**
